### ISSUE TITLE
GENESIS null model not working

### ISSUE THREAD

**Issue by whtop** [xihaoli/STAARpipeline-Tutorial#27]
When genesis null model is used in the code below, it returns: dsyMatrix not supported

results_individual_analysis <- Individual_Analysis(chr=chr,start_loc=start_loc,end_loc=end_loc,
                                                     genofile=genofile,obj_nullmodel=obj_nullmodel,mac_cutoff=20,
                                                     QC_label=QC_label,variant_type=variant_type,
                                                     geno_missing_imputation=geno_missing_imputation)

**Comment by xihaoli** [comment]
Hi @whtop,

Thanks for reaching out. May I ask whether you have converted the genesis null mode to STAAR null model, using the `genesis2staar_nullmodel()` function? If the problem still persists, then the issue may be on the class (type) of `Sigma_i` from the null model object `obj_nullmodel`, which can be fixed by setting `as(Sigma_i, "dsCMatrix")`.

Best,
Xihao

**Comment by whtop** [comment]
Thank you!

This is exactly I do: as(Sigma_i, "dsCMatrix").
