### ISSUE TITLE
Expected input Parameters for Gene Centric Coding Step

### ISSUE THREAD

**Issue by cantlap** [xihaoli/STAARpipeline-Tutorial#29]
Whenever I run the Gene Centric Coding Step I get this error regardless of how many arguments or what the argument is that I input. What is the pipeline expecting as input?

[1] 379
[1] 701
# of selected samples: 0
# of selected variants: 207
# of selected samples: 0
# of selected variants: 29
# of selected samples: 0
# of selected variants: 0
Error in data.frame(id.genotype, index = seq(1, length(id.genotype))) : 
  arguments imply differing number of rows: 0, 2
Calls: Gene_Centric_Coding -> coding -> data.frame
Execution halted

**Comment by xihaoli** [comment]
Hi @cantlap,

Thanks for your question. With a quick look, the issue seems likely due to your sample ids in genotype (stored in your annotated GDS file) and phenotype (stored in your null model object) not matching, such that the number of selected samples is always 0. Could you please check on this?

Note that both the annotated GDS file and the null model object are the expected inputs in the STAARpipeline.

Hope this helps.

Best,
Xihao

**Comment by cantlap** [comment]
That was the exact issue thank you! It looks like PLINK added a "0_" to the beginning of each ID when making bfiles. I just needed to add the same "0_" to the gds files to match them up.
