### ISSUE TITLE
variant set in gene-centric coding/noncoding analysis

### ISSUE THREAD

**Issue by eliu98** [xihaoli/STAARpipeline-Tutorial#65]
Hi Dr. Li,

I am running the STAARPipeline with a relatively small sample size (~1000 samples), which limits the number of rare variants in the rare variant set, especially when they are grouped based on their functional annotations. Is there a way to combine/customize the variants sets before testing (i.e. I'd like to combine the pLof and missense variants for each gene so that I will have more variants in each variant set)?

Also, how is the alpha levels determined in the sliding window and dynamic window analyses? 

Thank you!

Best,
Elaine

**Comment by xihaoli** [comment]
Dear Elaine,

Thanks for your questions. Yes, while developing and maintaining STAARpipeline, we have expanded its usage by allowing for (1) combining and (2) customizing the variant sets before testing. Currently, these additional functionalities are in the final testing and polishing stage. Please [send me a note](mailto:xihaoli@unc.edu) for me to share so that you can make use of it.

Best,
Xihao

**Comment by eliu98** [comment]
Thank you!
