### ISSUE TITLE
Error when Running "STAARpipeline_Null_Model.r"

### ISSUE THREAD

**Issue by mzw-jyz** [xihaoli/STAARpipeline-Tutorial#73]
Hi Xihao,

I am currently using the STAARpipeline tool for data association analysis and encountered the following issues while running  "STAARpipeline_Null_Model.r":

**1.**The fit_nullmodel function requires factor variables (e.g., as.factor(study_ethnicity)) to have at least two different levels (categories). However, all the values in the study_ethnicity column are 1 (indicating all samples belong to the Han ethnicity), so I removed this column from the data.

**2.**After adjusting the code and rerunning the model, the following warning messages appeared:
·Large variance estimate observed in the iterations, model not converged...
·Variance estimate on the boundary of the parameter space observed, refitting model...

**3.**My purpose in conducting STAARpipeline data association analysis is to compare the results with the previous GWAS data association analysis. To ensure the comparability of the results, I adjusted obj_nullmodel to align with the GWAS data. The adjusted code is as follows:

obj_nullmodel <- fit_nullmodel(
  ln_mt ~ age + gender + pc1 + pc2 + BMI,
  data = phenotype,
  kins = sgrm,
  use_sparse = TRUE,
  kins_cutoff = 0.0442,
  id = "IID",
  family = gaussian(link = "identity"),
  verbose = TRUE
)

However, the warning messages persisted. I have attached the detailed error log in the attachment for your reference.
[Error log.docx](https://github.com/user-attachments/files/18128406/Error.log.docx)

Additionally, I checked the GRM file and found negative values in it. Could this be the cause of the issue? If so, how should I address it?
Finally, I have one additional question: In this models, the variable age2 is included. What does age2 represent, and why is it necessary to include this variable in the model?
I would greatly appreciate your help in resolving these issues. Thank you very much for your time and support!
 
Best regards,
Mozhiwen

**Comment by yuxinyuanqt** [comment]
Hi @mzw-jyz,

Thank you for your detailed questions. I’ll address them point by point to help resolve the issues:

**1. Excluding study_ethnicity**
If all values in the _study_ethnicity_ column are 1, it provides no variability and should be excluded from the model. You handled this correctly.

**2. Warnings and GRM File Issues**
The convergence issue ("Variance estimate on the boundary of the parameter space observed") occurs because theta[1] tends toward infinity and theta[2] = 0. This may depend on a list of practical considerations,such as:
- Trait type (continuous/binary).
- Whether continuous traits follow a normal distribution (consider rank-based inverse normal transformation (INT) if not).
- Proper generation of the GRM (sgrm).
- Inclusion of all plausible covariates in the null model.
Regarding the GRM, negative values are not uncommon. These negative values should not affect the results. The _kins_cutoff_ parameter (default = 0.022) can be used to set values below this threshold to 0, ensuring the output matrix is sparse and block-diagonal.

**3. Ensuring Comparability with GWAS**
If your goal is to compare results between STAARpipeline and a previous GWAS analysis, it is essential to ensure consistency in analysis strategies. This includes:
- Using the same set of covariates.
- Applying the same normalization to continuous traits, such as rank-based inverse normal transformation (INT) for ln_mt.
- Verifying that both analyses use the same GRM.

**4. Clarification on age2**
The variable _age2_ typically represents the square of age (i.e., age^2). Including _age2_ as a covariate helps account for potential nonlinear effects of age on the phenotype, ensuring better adjustment for the influence of age.

I hope this helps resolve the issues you’ve encountered. Please feel free to share any additional questions or updates.

Best,
Yuxin

**Comment by mzw-jyz** [comment]
Dear Yuxin,

Thank you very much for your detailed responses earlier! Based on your suggestions, I have systematically completed the relevant adjustments and validations. However, when re-running the "STAARpipeline_Null_Model.r" script, I still encountered some issues. Below is an update on my progress and the current questions I have:

**1. Adjustments and Validations Completed**
- Phenotype ID Matching: Corrected the phenotype data's IID to match the GRM format and ensured their order is consistent.
- Handling Negative GRM Values: Set all GRM values below the kins_cutoff of 0.0442 to 0 to ensure matrix sparsity.
- Phenotype Confirmation: The ln_mt variable was log-transformed and now approximates a normal distribution. Added age2 to the model to account for potential nonlinear effects.
- Consistency with GWAS Analysis: Excluded samples with kinship > 0.0442 and ensured GRM, covariates, and ln_mt standardization are consistent with GWAS analysis.

**2. Current Issues**
- Model Fitting Warnings: Encountered warnings such as “model not converged” and “variance estimate on the boundary.” The genetic variance component (kins1) consistently remains 0 despite adjustments.
- Low Variability in GRM: GRM values are concentrated around 0.5, and excluding high-relatedness samples may have further reduced variability and weakened genetic signals.
- Weak Genetic Signals: Weight adjustments for high-value samples (ln_mt > 6) showed limited improvement in model performance.

**3. Current Questions**
- Could the warnings during model fitting be caused by kins1 = 0 in the GRM? If so, are there alternative methods to optimize the GRM or improve model performance?
- Does kins1 = 0 indicate that genetic signals have minimal influence on melatonin concentration? Is it still worthwhile to proceed with STAARpipeline analysis?

The attachment includes the detailed error log ([Error_log2.docx](https://github.com/user-attachments/files/18136255/Error_log2.docx)) for your reference.
Thank you for your patience and guidance!I look forward to your valuable insights.

Best regards,
Mozhiwen

**Comment by xihaoli** [comment]
Hi Mozhiwen,

Thanks for the updates. If your GRM is already a sparse matrix, then the `kins_cutoff` won't be invoked when fitting the null model. This parameter will be invoked when your GRM is a dense matrix. Given that you "excluded samples with kinship > 0.0442 and ensured GRM, covariates, and ln_mt standardization are consistent with GWAS analysis", it seems like you would like to only keep samples that tend to be independent? If this is the case, and since your estimated kins1 = 0 from the output, you could try fit the null model again without the GRM (that is, setting `kins = NULL`).

Best,
Xihao

**Comment by mzw-jyz** [comment]
Hi Xihao,

Thank you for your detailed suggestions. Following your advice, I removed the GRM (kins = NULL) when fitting the null model. I’m happy to report that the model was successfully fitted without any warning messages, and the results look consistent.

Thank you again for your time and support!

Best regards,
Mozhiwen

**Comment by xihaoli** [comment]
No problem. Please raise an issue (or reopen this one) if you have any additional questions. Closing this issue for now.
